spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    com.capgemini.test.code.clients: DEBUG
    feign: DEBUG

external:
  service:
    url: http://localhost:1080
